/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Color;
import java.util.Date;
import controlador.CONTROL_USUARIOS;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class FORMULARIO_TARJETA extends javax.swing.JFrame {

    /**
     * Creates new form FORMULARIO_PASAJERO
     */
    String nombre,apellido,cedula1,sexo,correo,usuario,contraseña,nombrecompleto,tipo1,placa,marca,modelo,color,asientos;
    Date fechanac,fechali1;
    public FORMULARIO_TARJETA(String nombre,String apellido,String cedula1,String sexo,String correo,Date fechanac,String usuario,String contraseña) {
        initComponents();
        TITULAR.setText(nombre+" "+apellido);
        TITULAR.setEditable(false);
        this.nombre = nombre;
        this.apellido = apellido;
        this.cedula1 = cedula1;
        this.sexo = sexo;
        this.correo = correo;
        this.fechanac = fechanac;
        this.usuario = usuario;
        this.contraseña = contraseña;
        
    }
    public FORMULARIO_TARJETA(){
    
    }
    public FORMULARIO_TARJETA(String nombre,String apellido,String cedula1,String sexo,String correo,Date fechanac
            ,String usuario,String contraseña,String tipo,Date 
                    fechali,String placa1,String marca1,String modelo1,String color1, String asientos1 ){
        initComponents();
        TITULAR.setText(nombre+" "+apellido);
        TITULAR.setEditable(false);
        this.nombre = nombre;
        this.apellido = apellido;
        this.cedula1 = cedula1;
        this.sexo = sexo;
        this.correo = correo;
        this.fechanac = fechanac;
        this.usuario = usuario;
        this.contraseña = contraseña;
        this.fechali1=fechali;
        this.tipo1=tipo;
        this.placa = placa1;
        this.marca = marca1;
        this.modelo = modelo1;
        this.color = color1;
        this.asientos = asientos1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TITULAR = new javax.swing.JTextField();
        numero = new javax.swing.JFormattedTextField();
        jMonthChooser1 = new com.toedter.calendar.JMonthChooser();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        registrarse = new javax.swing.JButton();
        regresar = new javax.swing.JButton();

        setUndecorated(true);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("POLIDRIVER"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de la Tarjeta"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Titular:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel3.setText("Número de la Tarjeta:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel4.setText("Fecha de expiración:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));
        jPanel2.add(TITULAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 200, -1));

        try {
            numero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#### #### #### ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 200, -1));
        jPanel2.add(jMonthChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, 30));
        jPanel2.add(jYearChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 540, 200));

        registrarse.setText("Registrase");
        registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarseActionPerformed(evt);
            }
        });
        jPanel1.add(registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 110, -1));

        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        jPanel1.add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 110, -1));

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        if(tipo1==null){
        
            FORMULARIO_PASAJERO fp =new FORMULARIO_PASAJERO(nombre, apellido, cedula1, sexo, correo, fechanac, usuario, contraseña);
            fp.setLocationRelativeTo(null);
            fp.setVisible(true);
            this.dispose();
        }else{
            FORMULARIO_VEHICULO fv = new FORMULARIO_VEHICULO(nombre, apellido, cedula1, sexo, correo, fechanac, usuario, contraseña, tipo1, fechali1,placa,marca,modelo,color,asientos);
            fv.setLocationRelativeTo(null);
            fv.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_regresarActionPerformed

    private void registrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarseActionPerformed
        CONTROL_USUARIOS con = new CONTROL_USUARIOS();
        if(numero.getText().isEmpty()==false){
            
            
            if(tipo1==null)
            {
                boolean c = con.control_guardado_pasajero(nombre, apellido,cedula1,  sexo, correo,fechanac.toString(), usuario, contraseña);
                JOptionPane.showConfirmDialog(null, "Sus datos se han registrado en el sistema", "Registro Exitoso", JOptionPane.DEFAULT_OPTION);
                con.control_guardadotarjeta(cedula1, TITULAR.getText(), numero.getText(), String.valueOf(jMonthChooser1.getMonth()+"/"+String.valueOf(jYearChooser1.getYear())));
                FORMULARIO_LOGIN log = new FORMULARIO_LOGIN();
                log.setVisible(true);
                log.setLocationRelativeTo(null);
                this.dispose();
            }
            else
            {
                boolean c=con.control_guardado_conductor(nombre, apellido, cedula1, sexo, correo, fechanac.toString(), usuario, contraseña, tipo1, fechali1);
                boolean cv=con.control_guardado_conductor_vehiculo(cedula1, nombre,apellido, placa, marca, modelo, color, asientos);
                boolean ct = con.control_guardadotarjeta(cedula1, TITULAR.getText(),numero.getText(), String.valueOf(jMonthChooser1.getMonth()+"/"+String.valueOf(jYearChooser1.getYear())));
                JOptionPane.showConfirmDialog(null, "Sus datos se han registrado en el sistema", "Registro Exitoso", JOptionPane.DEFAULT_OPTION);
                FORMULARIO_LOGIN log = new FORMULARIO_LOGIN();
                log.setVisible(true);
                log.setLocationRelativeTo(null);
                this.dispose();
            }
        }else {
        JOptionPane.showConfirmDialog(null, "Ingresar el número de tarjerta", "Campos faltantes", JOptionPane.DEFAULT_OPTION);
        }
    }//GEN-LAST:event_registrarseActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TITULAR;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private com.toedter.calendar.JMonthChooser jMonthChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    private javax.swing.JFormattedTextField numero;
    private javax.swing.JButton registrarse;
    private javax.swing.JButton regresar;
    // End of variables declaration//GEN-END:variables
}
