/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Color;
import controlador.CONTROL_USUARIOS;
import java.util.Date;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class FORMULARIO_VEHICULO extends javax.swing.JFrame {

    /**
     * Creates new form FORMULARIO_PASAJERO
     */
    String nombrec,apellidoc,cedulac,sexoc,correoc,usuarioc,contraseñac,tipoc;
    Date fechanaci,fechalice;
    String placat,marcat,modelot,colort,numt;
    public FORMULARIO_VEHICULO() {
        initComponents();
        modelo.setText("");
        marca.setText("");
        colrcarro.setText("");
        registrarse.setEnabled(true);
    }    
    public FORMULARIO_VEHICULO(String nombre1,String apellido1, String cedula1,String sexo1, String correo1,Date fechanac
            ,String Usuario1,String contraseña1,String tipo1,Date fechali  ){
       initComponents();
       this.nombrec = nombre1;
       this.apellidoc = apellido1;
       this.cedulac = cedula1;
       this.sexoc = sexo1;
       this.correoc = correo1;
       this.fechanaci = fechanac;
       this.fechalice = fechali;
       this.usuarioc = Usuario1;
       this.contraseñac = contraseña1;
       this.tipoc = tipo1;
       
    }
    public FORMULARIO_VEHICULO(String nombre1,String apellido1, String cedula1,String sexo1, String correo1,Date fechanac
            ,String Usuario1,String contraseña1,String tipo1,Date fechali,
            String placa1,String marca1,String modelo1,String color1,String num1){
       initComponents();
       this.nombrec = nombre1;
       this.apellidoc = apellido1;
       this.cedulac = cedula1;
       this.sexoc = sexo1;
       this.correoc = correo1;
       this.fechanaci = fechanac;
       this.fechalice = fechali;
       this.usuarioc = Usuario1;
       this.contraseñac = contraseña1;
       this.tipoc = tipo1;
       this.placat= placa1;
       this.marcat= marca1;
       this.modelot = modelo1;
       this.colort = color1;
       this.numt = num1;
       placa.setText(placa1);
       modelo.setText(modelo1);
       marca.setText(marca1);
       colrcarro.setText(color1);
       asientos.setSelectedItem(num1);
    }
    public FORMULARIO_VEHICULO(String placa1,String marca1,String modelo1,String color1, String num1){
        initComponents();
        this.placat= placa1;
        this.marcat = marca1;
        this.modelot = modelo1;
        this.colort = color1;
        this.numt = num1;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        modelo = new javax.swing.JTextField();
        marca = new javax.swing.JTextField();
        asientos = new javax.swing.JComboBox<>();
        placa = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        colrcarro = new javax.swing.JTextField();
        registrarse = new javax.swing.JButton();
        regresar = new javax.swing.JButton();

        setUndecorated(true);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("POLIDRIVER"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Vehículo"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Placa:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel3.setText("Marca:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel4.setText("Modelo:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel5.setText("Número de asientos:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));
        jPanel2.add(modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 150, -1));
        jPanel2.add(marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 150, -1));

        asientos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6" }));
        jPanel2.add(asientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 150, -1));

        try {
            placa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("???-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 150, -1));

        jLabel1.setText("Color:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));
        jPanel2.add(colrcarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 150, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 420, 270));

        registrarse.setText("Siguiente");
        registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarseActionPerformed(evt);
            }
        });
        jPanel1.add(registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 110, -1));

        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        jPanel1.add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 110, -1));

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        FORMULARIO_CONDUCTOR fc = new FORMULARIO_CONDUCTOR(nombrec, apellidoc, cedulac, sexoc, correoc, fechanaci, usuarioc, contraseñac, tipoc, fechalice);
        fc.setLocationRelativeTo(null);
        fc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_regresarActionPerformed

    private void registrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarseActionPerformed
        CONTROL_USUARIOS cu = new CONTROL_USUARIOS();
        
        if(cu.validar_campos_vehiculo(placa, marca, modelo, colrcarro)){
            FORMULARIO_TARJETA ft = new FORMULARIO_TARJETA(nombrec, apellidoc, cedulac, sexoc, correoc, fechanaci, usuarioc, contraseñac, tipoc, fechalice,placa.getText()
            ,marca.getText(),modelo.getText(),colrcarro.getText(),asientos.getSelectedItem().toString());
            ft.setLocationRelativeTo(null);
            ft.setVisible(true);
            this.dispose();
        }else 
        JOptionPane.showConfirmDialog(null, "Ingresar datos válidos", "Campos erroneos", JOptionPane.DEFAULT_OPTION);
      
    }//GEN-LAST:event_registrarseActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> asientos;
    private javax.swing.JTextField colrcarro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField marca;
    private javax.swing.JTextField modelo;
    private javax.swing.JFormattedTextField placa;
    private javax.swing.JButton registrarse;
    private javax.swing.JButton regresar;
    // End of variables declaration//GEN-END:variables
}
